### ISSUE TITLE
Using SWRLAPI with generated Java code

### ISSUE THREAD

**Issue by sagilar** [protegeproject/swrlapi-example#1]
Hi,

I am trying to use the SWRLAPI to run some rules/inferences in a dynamic application with Java.
I firstly designed my ontology, then, I exported the Java code using the Protégé code generation plugin. I made an application with the generated classes and they are ok, but when trying to use the SWRLEngine to perform the inferences (from the SWRL rules) it throws nothing important (compared to the results obtained in Protégé).
I am not sure if the generated Java code contains the SWRL rules embedded, or what can I do to use them in Java?

```
SWRLRuleEngine swrlEngine = SWRLAPIFactory.createSWRLRuleEngine(ontology);
swrlEngine.infer();
Set<OWLAxiom> inferredOWLAxioms = swrlEngine.getInferredOWLAxioms();
for(OWLAxiom axiom : inferredOWLAxioms)
    {
         System.out.println("Inferred axiom: " + axiom);
    }

--------------------------------------------------------------------------------------
Output: Inferred axiom: SameIndividual(<send-piece-material-data-service> )
Inferred axiom: SameIndividual(<request-piece-material-data-function> )
Inferred axiom: SameIndividual(<piece-data> )
Inferred axiom: SameIndividual(<semantic-application-interoperability> )
Inferred axiom: SameIndividual(<product-asset-b> )
Inferred axiom: SameIndividual(<application-complex-discrete-dynamics-model> )
Inferred axiom: SameIndividual(<s1_ba> )
Inferred axiom: SameIndividual(<process-c> )
Inferred axiom: SameIndividual(<resource-state-4> )
...

```
All the inferences are similar, not important information is given.

P.S:
- I also noticed the `swrlEngine.createSWRLRule(string, string1);` command, but I have many rules and I would want to avoid declaring them again.
- I have run the SWRL rules of my ontology in Protégé and it gives pretty interesting results, as the rule states. So, the rules are not the problem.

Any idea?

Many thanks in advance.

Santiago

**Comment by martinjoconnor** [comment]
Can you post the ontology. (Change .owl extension to .txt because GitHub does not allow the former.)

**Comment by sagilar** [comment]
Here is the ontology:
I have tried some things else:
- I ran the ontology in Java by calling the ontology file:
```
OWLOntologyManager ontologyManager = OWLManager.createOWLOntologyManager();
            OWLOntology ontology = ontologyManager.loadOntologyFromOntologyDocument(new File("Automation-I4.0-Min-Ontology.owl"));
```
Unfortunately, it does not run. It always shows an error when loading the ontology and making the reasoning: 

> [Line: 1, Column: 1]: built-in exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: cannot convert value of type rdf:PlainLiteral to xsd:string.

If I try to delete this rule, any other rule or query containing a similar statement `swrlb:contains(?somevariable,"anystring")` makes the error to occur.
- I went to Protégé again and tried to change the SWRL rules with such problem. I changed `swrlb:contains(?somevariable,"anystring"^^rdf:PlainLiteral)` which Protégé shows me by default, to `swrlb:contains(?somevariable,"anystring"^^xsd:string)`. It seems to be fine when changing the rules; I save and close, but when opening again, Protégé shows me the same `"anystring"^^rdf:PlainLiteral` in any declared string.
- I tried some SQWRL queries in Protégé with the `swrlb:contains(?somevariable,"anystring")` and it throws me the same error. The rules and queries that do not involve this statement, are ok.

I need to say that Pellet is the only reasoner that runs well with my ontology, at least in Protégé. Should I consider to set the Pellet reasoner in the Java code?

Many thanks in advance.



---------------------------------------

## Edited:
I commented out the rules where the `swrlb:contains(?somevariable,"anystring")` statement appears and now the ontology and the reasoner are working.
To correct the swrlb:contains problem I changed some `<Literal>anystring</Literal>` to `<Literal datatypeIRI="http://www.w3.org/2001/XMLSchema#string">anystring</Literal>`. It does not work yet, but at least Protégé does not show `^^rdf:PlainLiteral` in the rules of the SWRL Tab anymore.
I'm not sure what is causing the problem, maybe you can explain me better.

The other thing is that after commenting out the conflict rules, I run the reasoner in the Java code and it prints several inferred results with the next code:
```
SWRLRuleEngine swrlEngine = SWRLAPIFactory.createSWRLRuleEngine(ontology);
            swrlEngine.infer();
            Set<OWLAxiom> inferredOWLAxioms = swrlEngine.getInferredOWLAxioms();
            for(OWLAxiom axiom : inferredOWLAxioms)
            {
                System.out.println("Inferred axiom: " + axiom);
            }
```
The inferences look like not being too important and information-provider, how could I select only the important ones? is there any way?
I added a txt file with some of the result inferences, this way, perhaps you can explain me better how to understand them (and use correctly).

Many many thanks in advance.

BR,
Santiago


[inferences.txt](https://github.com/protegeproject/swrlapi-example/files/2794741/inferences.txt)


[Automation-I4.0-Min-Ontology - textformat.txt](https://github.com/protegeproject/swrlapi-example/files/2794584/Automation-I4.0-Min-Ontology.-.textformat.txt)

**Comment by sagilar** [comment]
Hi again.
I tried with different resources and it is running fine in the java code, but only when I comment out the SWRL rules and SQWRL queries with problems, i.e., all the SWRL rules and SQWRL queries which has a swrlb:contains(?somevariable,"anystring").
I have done many things to check if the error disappears where the code is failing:
```
<BuiltInAtom IRI="http://www.w3.org/2003/11/swrlb#contains">
                <Variable IRI="#cont"/>
                <Literal datatypeIRI="http://www.w3.org/2001/XMLSchema#string">SoftwareResource</Literal>
</BuiltInAtom>
```
or
```
<BuiltInAtom IRI="http://www.w3.org/2003/11/swrlb#contains">
                <Variable IRI="#cont"/>
                <Literal>SoftwareResource</Literal>
</BuiltInAtom>
```
even
```
<BuiltInAtom IRI="http://www.w3.org/2003/11/swrlb#contains">
                <Variable IRI="#cont"/>
                <Literal datatypeIRI="xsd:string">SoftwareResource</Literal>
</BuiltInAtom>
```

Unfortunately, no one has worked. Also in the Protégé interface with "SoftwareResource" or "SoftwareResource"^^xsd:string but no luck!
I could comment out to test the other rules and queries, but it is essential to count on them.

P.S:
I am sure that in previous tests all these rules and queries worked; I don't know if it is because of some new pluggin or perhaps it happened after merging the ontologies (I merged some ontologies previously in the code that I'm doing the tests).

--------------------------------------------

The complete errors are described here, which were obtained from the Protégé tabs:
SQWRL error:
```
Using Drools for query execution.

Exception running SQWRL query QueryActiveStates: error running SQWRL queries: error inserting asserted OWL axioms into Drools:
[Error: invoker.invoke("QueryServicesWithDatabaseContent", "swrlb:contains", 0, false, new VPATH($s), new BAVNs("sd", ""), $sd, new L("database", "xsd:string")): built-in exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: cannot convert value of type PlainLiteral to xsd:string]
[Near : {... invoker.invoke("QueryServicesW ....}]
             ^
[Line: 1, Column: 1]: built-in exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: cannot convert value of type PlainLiteral to xsd:string: exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: cannot convert value of type PlainLiteral to xsd:string: cannot convert value of type PlainLiteral to xsd:string: error inserting asserted OWL axioms into Drools:
[Error: invoker.invoke("QueryServicesWithDatabaseContent", "swrlb:contains", 0, false, new VPATH($s), new BAVNs("sd", ""), $sd, new L("database", "xsd:string")): built-in exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: cannot convert value of type PlainLiteral to xsd:string]
[Near : {... invoker.invoke("QueryServicesW ....}]
             ^
[Line: 1, Column: 1]: built-in exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: cannot convert value of type PlainLiteral to xsd:string: exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: cannot convert value of type PlainLiteral to xsd:string: cannot convert value of type PlainLiteral to xsd:string: [Error: invoker.invoke("QueryServicesWithDatabaseContent", "swrlb:contains", 0, false, new VPATH($s), new BAVNs("sd", ""), $sd, new L("database", "xsd:string")): built-in exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: cannot convert value of type PlainLiteral to xsd:string]
[Near : {... invoker.invoke("QueryServicesW ....}]
             ^
[Line: 1, Column: 1]: built-in exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: cannot convert value of type PlainLiteral to xsd:string: exception thrown by built-in swrlb:contains in rule QueryServicesWithDatabaseContent: cannot convert value of type PlainLiteral to xsd:string: cannot convert value of type PlainLiteral to xsd:string
```

SWRL error:
```
The SWRLAPI supports an OWL profile called OWL 2 RL and uses an OWL 2 RL-based reasoner to perform reasoning.
See the 'OWL 2 RL' sub-tab for more information on this reasoner.Exception running rule engine: error running Drools rule engine:
Exception executing consequence for rule "AssignmentDueToCharacteristicDevice" in defaultpkg: [Error: invoker.invoke("RuleForStandardInheritanceDevices", "swrlb:contains", 0, false, new VPATH(), new BAVNs("cont", ""), $cont, new L("Device", "xsd:string")): built-in exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: cannot convert value of type PlainLiteral to xsd:string]
[Near : {... invoker.invoke("RuleForStandar ....}]
             ^
[Line: 1, Column: 1]: built-in exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: cannot convert value of type PlainLiteral to xsd:string: Exception executing consequence for rule "AssignmentDueToCharacteristicDevice" in defaultpkg: [Error: invoker.invoke("RuleForStandardInheritanceDevices", "swrlb:contains", 0, false, new VPATH(), new BAVNs("cont", ""), $cont, new L("Device", "xsd:string")): built-in exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: cannot convert value of type PlainLiteral to xsd:string]
[Near : {... invoker.invoke("RuleForStandar ....}]
             ^
[Line: 1, Column: 1]: [Error: invoker.invoke("RuleForStandardInheritanceDevices", "swrlb:contains", 0, false, new VPATH(), new BAVNs("cont", ""), $cont, new L("Device", "xsd:string")): built-in exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: cannot convert value of type PlainLiteral to xsd:string]
[Near : {... invoker.invoke("RuleForStandar ....}]
             ^
[Line: 1, Column: 1]: built-in exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: cannot convert value of type PlainLiteral to xsd:string: exception thrown by built-in swrlb:contains in rule RuleForStandardInheritanceDevices: cannot convert value of type PlainLiteral to xsd:string: cannot convert value of type PlainLiteral to xsd:string
```

Many thanks in advance,

I keep waiting for your help, and go ahead with my project.

BR,

Santiago.

**Comment by martinjoconnor** [comment]
Sorry for the lack of response. I thought you were the same as the person on the Protege mailing list with a similar issue.

See: http://protege-project.136.n4.nabble.com/Protege-is-losing-xsd-string-type-when-I-re-open-it-td4671566.html

You can subscribe to this list here:

https://protege.stanford.edu/support.php

**Comment by sagilar** [comment]
Thanks for your quick response.

I returned to use the version 5.2; at least the datatypes are saved when closing protege.
I will prove the rules and queries there, and once done, post here again to check if the problem is the version 5.5 (which I have been using).

Have a good rest of day.

**Comment by sagilar** [comment]
After several attempts, I realized that I had to add the ^^xsd:string for every data property assertion that involved a string parameter. Now the SWRL rules and SQWRL queries are working again.
- This was done using the 5.2 version of Protégé. The 5.5 is presenting the bug as stated in the Protégé mailing list thread.


Thanks for your help.
